### 1 sec
numSamples <- 1000
x = read.csv(file="1_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="2_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="3_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="4_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="6_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="8_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 948)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="12_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="16_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="24_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM !=951)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="32_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="48_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="64_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 578)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="72_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM !=523)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="80_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM !=625)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="88_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 639)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="96_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 474)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="104_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 639)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="112_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 327)
sd(x$PRTIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="120_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 80 & x$ITERNUM != 797)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="128_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="160_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 503)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="192_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 26 & x$ITERNUM != 472 & x$ITERNUM != 922)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="224_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 321 & x$ITERNUM !=704)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
#sd(x$METIME)/mean(x$METIME)
x = read.csv(file="256_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 81)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="512_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 58 & x$ITERNUM != 186 & x$ITERNUM != 226)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="1024_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 46 & x$ITERNUM != 130 & x$ITERNUM != 214 & x$ITERNUM != 299)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="2048_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 166)
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
x = read.csv(file="4096_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= numSamples)
x <- subset(x, x$ITERNUM != 11 & x$ITERNUM != 32 & x$ITERNUM != 53 & x$ITERNUM != 74 & x$ITERNUM != 95 & x$ITERNUM != 116 & x$ITERNUM != 137 & x$ITERNUM != 158 & x$ITERNUM != 179 & x$ITERNUM != 200 & x$ITERNUM != 221 & x$ITERNUM != 242 & x$ITERNUM != 264) 
sd(x$PRTIME)
sd(x$METIME)
sd(x$PRTIME)/mean(x$PRTIME)
sd(x$METIME)/mean(x$METIME)
